language: python
python:
  - "2.7"
# command to install dependencies

before_install:
- java -version

install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  #- sudo apt-get install python default-jre-headless python-tk python-pip python-dev \ libxml2-dev libxslt-dev zlib1g-dev
  - sudo pip install bzt
  - sudo pip install --upgrade bzt

script:
  - pip bzt OpenCart.yml
